language: python
python:
    - 3.6
services:
    - docker
    - postgresql
install:
    - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres    
script:
    - docker-compose build
    #- docker-compose up
    #- docker-compose run pg_ctl -D /usr/local/var/postgres start
    #- docker-compose run web python manage.py migrate
    - docker-compose run web python manage.py test
