# .travis.yml

language: python
python:
    - 3.6
services:
    - docker
#    - postgres
install:
    - pip install -r requirements.txt
#before_script:
#    - psql -c 'create database testdb;' -U postgres
#    - psql -c 'create database travisci;' -U postgres
script:
#    - docker-compose build
#    - docker-compose run web python manage.py migrate
    - docker-compose run web python manage.py test
#    - python manage.py test
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mywebapp0
  run: python manage.py migrate
  on: master
