language: python
python:
    - 3.6
services:
    - docker
#    - postgres
install:
    - pip install -r requirements.txt

# undockerized
#before_script:
#    - psql -c 'create database testdb;' -U postgres
#    - psql -c 'create database travisci;' -U postgres

script:
#    - docker-compose build
    - docker-compose run web python manage.py test
#    - docker-compose run web python manage.py makemigrations
#    - docker-compose run web python manage.py migrate
# travis without dockerization
#    - python manage.py test

# undockerize, travis CI straight to heroku deployment
#deploy:
#    provider: heroku
#    api_key: $HEROKU_API_KEY
#    app: mywebapp0
#    run: python manage.py migrate
#    on: master
