language: python
python:
    - 3.6
services:
    - docker
#    - postgresql
before_install:
    # Let's stop postgresql
    - sudo service postgresql stop
    # wait for postgresql to shutdown
    - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
install:
    - pip install -r requirements.txt
#before_script:
#  - psql -c 'create database travisci;' -U postgres
script:
#    - docker-compose build
#    - docker-compose up
#    - docker-compose run pg_ctl -D /usr/local/var/postgres start
    - docker-compose run web python manage.py migrate
    - docker-compose run web python manage.py test
